const licores =
    [
        [
            ['Santiago Ruiz Albariño', '$' + 55, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Cauto Verdejo', '$' + 7 + ' / ' + '$' + 40, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Woodbridge Chardonnay', '$' + 7 + ' / ' + '$' + 35, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['La Crema Sonoma Coast Chardonnay', '$' + 50, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mer Solell Chardonnay', '$' + 80, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            []

        ],
        [
            ['19 Crimes Shiraz', '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Protos Roble Templranillo', '$' + 40, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Máequez de Arviza Tempranillo', '$' + 7 + ' / ' + '$' + 40, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mauro Tempranillo', '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Horse Heaven Hills H3 Cabaret', '$' + 9 + ' / ' + '$' + 55, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Hang TIme Plnot Noir', '$' + 45, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Red Schooner Malbec', '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Crasto Blend', '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['El Enemigo Malbec', '$' + 55, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Banfi Rosso Di Montalcino Sanglovese', '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['C.V.N.E Roble Tempranillo', '$' + 35, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
        ],
        [
            ['Minuti', '$' + 7 + ' / ' + '$' + 40, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Cote Rose   ', '$' + 40, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Chandon Rosé', '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Chandon Delice', '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Moët & Chandon Nectar Imperial', '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mvsa Brut', '$' + 7 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mvsa Rose', '$' + 7 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ["Graham's Fine Ruby", '$' + 7 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Oremus Tokaji Aszu 3 Puttonyos', '$' + 7 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mouton Cadet Resetve', '$' + 7 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Old Par 12', '$' + 7 + ' / ' + '$' + 90, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Johnny Walker Black Label', '$' + 7 + ' / ' + '$' + 90, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ["Buchannan's 12", '$' + 7 + ' / ' + '$' + 90, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ["Buchannan's 18", '$' + 10 + ' / ' + '$' + 160, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Macallan 12', '$' + 9 + ' / ' + '$' + 115, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Glenmmorangie 10', '$' + 9 + ' / ' + '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ["Glenmmorangie Nectar D'OR", '$' + 11 + ' / ' + '$' + 125, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
        ],
        [
            ['Bombay Sapphire', '$' + 7 + ' / ' + '$' + 80, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Tanqueray', '$' + 7 + ' / ' + '$' + 80, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Tanqueray Ten', '$' + 8 + ' / ' + '$' + 95, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Martin Miller', '$' + 8 + ' / ' + '$' + 95, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Acompañantes', '$' + 2, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Seco', '$' + 5 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Ron Abuelo Añeojo', '$' + 5 + ' / ' + '$' + 60, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Ron Abuelo 7', '$' + 7 + ' / ' + '$' + 95, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Ron Abuelo 12', '$' + 8 + ' / ' + '$' + 120, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Zacapa 23', '$' + 8 + ' / ' + '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Santa Teresa 1796', '$' + 8 + ' / ' + '$' + 100, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Don Julio Blanco', '$' + 7 + ' / ' + '$' + 95, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Don Julio Reposado', '$' + 8 + ' / ' + '$' + 105, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Absolut', '$' + 6 + ' / ' + '$' + 80, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Grey Goose', '$' + 7 + ' / ' + '$' + 95, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
            [],
        ],
        [
            ['Panama', '$' + 4, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Balboa', '$' + 4, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Palenque', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Catalina', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['River Down', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Corona', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Stella Artois', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Heineken', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Modelo', '$' + 6, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Chelada', '$' + 0.5, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Michelada', '$' + 1.5, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
        ],
        [
            ['Mojito Clásico', '$' + 8, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Mojito Maracuya', '$' + 8, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Margarita', '$' + 8, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Panama Hat', '$' + 8, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['Piña Colada', '$' + 8, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['El Refrigerio', '$' + 7, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            ['La Mediciona', '$' + 7, 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Debitis, esse.', ["Fresco", "Frio", "Lorem"]],
            [],
            [],
            [],
            [],
        ]

    ]

export default licores